# Generated by Django 4.1.3 on 2023-01-07 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataadministrator', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CharacterStats',
            new_name='Character',
        ),
    ]
